### ISSUE TITLE
We got 32bit working for basically everything, along with arm32, and arm64 on linux

### ISSUE THREAD

**Issue by Bioblaze** [OS-of-S/Godot_LinuxLibsInstaller#1]
If you wanna look over our code here, and update your stuff

https://github.com/blazium-engine/ci_cd

its in the .github/workflows folder each broken down.

If you have any suggestions, would love to have them <3

Right now we're working on the macos/ios building on linux part ourselves. We're maybe 1/3rd the way there? maybe 1/5th? idk

Getting closed none the less.

Love the repo, ran across it randomly lol while searching for some issues with osxcross

**Comment by OS-of-S** [comment]
Hi there!

Thank you for the issue, I looked inside your scripts. It's really nice, especially that arm32 and arm64 sdk also provided and if it work from one Linux base for all bit-types.

I'm not going to implement your solutions in the near future (too busy now and other reasons) but I took a note on this case. I may come back to it if I get into Godot compiling again. Thanks!

**Comment by Bioblaze** [comment]
kk, thought it would help.

Right now we're stuck on solving the ubuntu macos/ios crap.

We looked over your notes in your script, good stuff.

If you have any ideas welcome to accept them over on our side of the pond.

Also if you wanna drop down for a visit: https://discord.gg/ejDAdcmZ57

<3 wouldn't mind having a chat about ci/cd stuff.

Be safe, and god bless <3
